enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config



[GooglePhotos]
build-mode = "both"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"
